// <auto-generated />
namespace _5204_passion_project_n01446543.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cards_and_decks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cards_and_decks));
        
        string IMigrationMetadata.Id
        {
            get { return "202102180230582_cards_and_decks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
